### ISSUE TITLE
ccs9/TMS570LC43x doesn't match target endianness

### ISSUE THREAD

**Issue by osama1199** [YashBansod/ARM-TMS570LC43x-CCS-HALCoGen#1]
I am try to execute the example code on tms570lc43x launchpad but i am getting the same error each time. 
"Doesn't match target endianness, not loaded. Check project build option and target configuration"
compiler version:TI v20.2.1.LTS (i also tried 15 and 18 LTS compiler version as well but it doesn't work)
Device endianness : be32
output format: eabi(ELF)
runtime support library: rtsv7R4_T_be_v3D16_eabi.lib

**Comment by YashBansod** [comment]
Can you try running the example codes provided in HALCoGen in your configuration? They should run by default.

The error seems to be because of improper configuration of your CCS project and not because of anything in the code. 
This code was written in CCS6, but maybe things have changed in your version of CCS.

If you are able to run the example codes provided in HALCoGen, then you can use these codes with the appropriate configuration in CCS and HALCoGen.

I would be able to help you if I could replicate your error, but unfortunately I cannot.

**Comment by osama1199** [comment]
Thanks

I have checked these example are for TMS570LC43x but the launchpad i am using has RM57lx chip so that was the problem and now i have check some example but there are not so many example for this chip.

Thanks
